### ISSUE TITLE
Swap sides not work

### ISSUE THREAD

**Issue by amnweb** [outofsync42/select-compare-tabs#1]
Swap sides not work, there is error

**Cannot read properties of undefined (reading 'document')**

![image](https://github.com/outofsync42/select-compare-tabs/assets/16545063/23149096-b7d7-4476-b22f-cb95d4a21564)

**Comment by outofsync42** [comment]
Thank you for letting me know. vscode had introduced a bug a while back that caused the vscode.window.visibleTextEditors to return the files in different order. After compensating for that it looks like they reverted to the original way so i updated the swap to find the correct files when swapping. Should be working with latest update 1.0.3
